timeout: 900s
steps:

# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
         'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID', '.']

# Docker push where to go??
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID']

# Replacing string in kubernetes resource file
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      sed -i "s#@BUILD_ID@#$BUILD_ID#g" k8s/deployment.yaml
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s
  - --location=us-central1
  - --cluster=autopilot-cluster-1