apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtcapi-deployment
  labels:
    app: webrtcapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtcapi
  template:
    metadata:
      labels:
        app: webrtcapi
    spec:
      containers:
      - name: webrtcapi
        image: gcr.io/plated-shelter-329723/webrtcapi:@BUILD_ID@
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: webrtcapi-http
  namespace: development
spec:
  selector:
     run: webrtcapi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort